from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class LabInterfaceResult:
    external_reference: str
    access_url: str | None = None
    state: str | None = None


class LabInterface(Protocol):
    def provision(self, template_key: str, lab_id: int, user_id: int) -> LabInterfaceResult: ...
    def start(self, external_reference: str) -> LabInterfaceResult: ...
    def stop(self, external_reference: str) -> LabInterfaceResult: ...
    def reset(self, external_reference: str) -> LabInterfaceResult: ...
    def status(self, external_reference: str) -> LabInterfaceResult: ...
    def release(self, external_reference: str) -> LabInterfaceResult: ...
    def delete(self, external_reference: str) -> LabInterfaceResult: ...
